require("dotenv").config({ path: require("path").join(__dirname, ".env") });

const crypto = require("crypto");
const path = require("path");
const express = require("express");
const helmet = require("helmet");
const multer = require("multer");
const rateLimit = require("express-rate-limit");
const { Resend } = require("resend");

const app = express();
const port = Number(process.env.PORT || 3000);
const requiredEnvironmentVariables = [
  "RESEND_API_KEY",
  "EMAIL_FROM",
  "RECRUITMENT_EMAIL"
];

const missingEnvironmentVariables = requiredEnvironmentVariables.filter(
  (name) => !process.env[name] || !String(process.env[name]).trim()
);

if (missingEnvironmentVariables.length > 0) {
  console.error("\nBrownstone Careers could not start.");
  console.error(
    `Missing environment variable(s): ${missingEnvironmentVariables.join(", ")}`
  );
  console.error(
    "Create a .env file beside server.js or configure these values in your hosting dashboard."
  );
  console.error("See RESEND-SETUP.md for exact instructions.\n");
  process.exit(1);
}

const resend = new Resend(process.env.RESEND_API_KEY.trim());

app.set("trust proxy", 1);
app.disable("x-powered-by");
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json({ limit: "100kb" }));
app.use(express.urlencoded({ extended: true, limit: "100kb" }));

const publicDirectory = path.join(__dirname, "public");
app.use(express.static(publicDirectory, { extensions: ["html"] }));

const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  limit: 6,
  standardHeaders: true,
  legacyHeaders: false,
  message: { message: "Too many submissions. Please wait 15 minutes and try again." }
});

const allowedMimeTypes = new Set([
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
]);

const allowedExtensions = new Set([".pdf", ".doc", ".docx"]);

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024, files: 1, fields: 20 },
  fileFilter: (_request, file, callback) => {
    const extension = path.extname(file.originalname).toLowerCase();
    if (!allowedMimeTypes.has(file.mimetype) || !allowedExtensions.has(extension)) {
      return callback(new Error("Only PDF, DOC, and DOCX resumes are accepted."));
    }
    callback(null, true);
  }
});

function clean(value, maxLength = 5000) {
  return String(value ?? "").trim().slice(0, maxLength);
}

function escapeHtml(value) {
  return clean(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function validEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean(value, 160));
}

function createReference(prefix = "BC") {
  const date = new Date().toISOString().slice(0, 10).replaceAll("-", "");
  const random = crypto.randomBytes(3).toString("hex").toUpperCase();
  return `${prefix}-${date}-${random}`;
}

function senderAddress() {
  return process.env.EMAIL_FROM || "Brownstone Careers <applications@brownstonecareers.agency>";
}

function recruitmentAddress() {
  return process.env.RECRUITMENT_EMAIL || "support@brownstonecareers.agency";
}

function emailLayout(title, content) {
  return `<!doctype html>
  <html><body style="margin:0;background:#f2f5fa;font-family:Arial,Helvetica,sans-serif;color:#17233b">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f2f5fa;padding:30px 12px">
  <tr><td align="center">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#fff;border-radius:16px;overflow:hidden;border:1px solid #dfe6f0">
  <tr><td style="background:#071a3b;padding:26px 32px;color:#fff">
  <div style="font-size:22px;font-weight:800;letter-spacing:.08em">BROWNSTONE <span style="font-weight:400">CAREERS</span></div>
  <div style="font-size:9px;letter-spacing:.24em;margin-top:8px;color:#c9d4ea">RECRUITMENT AGENCY</div>
  </td></tr>
  <tr><td style="padding:32px"><h1 style="font-size:26px;line-height:1.25;margin:0 0 20px;color:#071a3b">${title}</h1>${content}</td></tr>
  <tr><td style="padding:18px 32px;background:#f7f9fc;color:#667085;font-size:12px;line-height:1.6">
  This email was generated by the official Brownstone Careers website. Never share passwords, PINs, or banking credentials.
  </td></tr></table>
  </td></tr></table></body></html>`;
}

async function sendEmail(payload) {
  if (!process.env.RESEND_API_KEY) {
    throw new Error("RESEND_API_KEY is not configured.");
  }

  const { data, error } = await resend.emails.send(payload);
  if (error) throw new Error(error.message || "Resend rejected the request.");
  return data;
}

app.get("/api/health", (_request, response) => {
  response.json({
    ok: true,
    emailConfigured: Boolean(process.env.RESEND_API_KEY),
    service: "Brownstone Careers"
  });
});

app.post("/api/applications", limiter, upload.single("resume"), async (request, response) => {
  try {
    if (clean(request.body.website)) return response.status(200).json({ success: true });

    const fields = {
      firstName: clean(request.body.firstName, 80),
      lastName: clean(request.body.lastName, 80),
      email: clean(request.body.email, 160),
      phone: clean(request.body.phone, 40),
      role: clean(request.body.role, 120),
      timezone: clean(request.body.timezone, 80),
      startDate: clean(request.body.startDate, 30),
      experience: clean(request.body.experience, 4000),
      interest: clean(request.body.interest, 3000),
      skills: clean(request.body.skills, 3000),
      readiness: clean(request.body.readiness, 2500),
      consent: clean(request.body.consent, 10)
    };

    const requiredValues = [
      fields.firstName, fields.lastName, fields.email, fields.phone, fields.role,
      fields.timezone, fields.startDate, fields.experience, fields.interest,
      fields.skills, fields.readiness
    ];

    if (requiredValues.some((value) => !value) || fields.consent !== "yes" || !request.file) {
      return response.status(400).json({
        message: "Please complete every required field, accept the consent statement, and attach your resume."
      });
    }

    if (!validEmail(fields.email)) {
      return response.status(400).json({ message: "Please enter a valid email address." });
    }

    const reference = createReference();
    const fullName = `${fields.firstName} ${fields.lastName}`;

    const recruiterContent = `
      <p><strong>Application reference:</strong> ${reference}</p>
      <p><strong>Candidate:</strong> ${escapeHtml(fullName)}</p>
      <p><strong>Email:</strong> ${escapeHtml(fields.email)}</p>
      <p><strong>Phone:</strong> ${escapeHtml(fields.phone)}</p>
      <p><strong>Role:</strong> ${escapeHtml(fields.role)}</p>
      <p><strong>Time zone:</strong> ${escapeHtml(fields.timezone)}</p>
      <p><strong>Available start:</strong> ${escapeHtml(fields.startDate)}</p>
      <h2 style="font-size:17px;margin:26px 0 8px;color:#071a3b">Relevant experience</h2>
      <p style="white-space:pre-line;line-height:1.7">${escapeHtml(fields.experience)}</p>
      <h2 style="font-size:17px;margin:26px 0 8px;color:#071a3b">Interest in the role</h2>
      <p style="white-space:pre-line;line-height:1.7">${escapeHtml(fields.interest)}</p>
      <h2 style="font-size:17px;margin:26px 0 8px;color:#071a3b">Software and technical skills</h2>
      <p style="white-space:pre-line;line-height:1.7">${escapeHtml(fields.skills)}</p>
      <h2 style="font-size:17px;margin:26px 0 8px;color:#071a3b">Remote-work readiness</h2>
      <p style="white-space:pre-line;line-height:1.7">${escapeHtml(fields.readiness)}</p>`;

    await sendEmail({
      from: senderAddress(),
      to: [recruitmentAddress()],
      replyTo: fields.email,
      subject: `New application: ${fields.role} — ${fullName} — ${reference}`,
      html: emailLayout("New Candidate Application", recruiterContent),
      attachments: [{
        filename: request.file.originalname.replace(/[^\w.\-() ]/g, "_"),
        content: request.file.buffer
      }]
    });

    const candidateContent = `
      <p style="font-size:16px;line-height:1.7">Dear ${escapeHtml(fields.firstName)},</p>
      <p style="font-size:16px;line-height:1.7">Thank you for applying for the <strong>${escapeHtml(fields.role)}</strong> opportunity with Brownstone Careers.</p>
      <div style="margin:24px 0;padding:18px;background:#eef3fb;border-left:4px solid #153c7a;border-radius:8px">
        <div style="font-size:12px;color:#5b6880;text-transform:uppercase;letter-spacing:.12em">Application reference</div>
        <div style="font-size:22px;font-weight:800;color:#071a3b;margin-top:5px">${reference}</div>
      </div>
      <p style="font-size:16px;line-height:1.7">Our recruitment team will review your submission. Keep this reference number for future correspondence.</p>
      <p style="font-size:16px;line-height:1.7">Regards,<br><strong>Brownstone Careers Recruitment Team</strong></p>`;

    try {
      await sendEmail({
        from: senderAddress(),
        to: [fields.email],
        replyTo: recruitmentAddress(),
        subject: `Application received — ${reference}`,
        html: emailLayout("Application Received", candidateContent)
      });
    } catch (confirmationError) {
      console.error("Candidate confirmation failed:", confirmationError.message);
    }

    return response.status(201).json({ success: true, reference });
  } catch (error) {
    console.error("Application submission error:", error);
    return response.status(502).json({
      message: "We could not deliver your application. Please try again or email support@brownstonecareers.agency."
    });
  }
});

app.post("/api/contact", limiter, upload.none(), async (request, response) => {
  try {
    if (clean(request.body.website)) return response.status(200).json({ success: true });

    const name = clean(request.body.name, 120);
    const email = clean(request.body.email, 160);
    const subject = clean(request.body.subject, 160);
    const message = clean(request.body.message, 5000);

    if (!name || !email || !subject || !message) {
      return response.status(400).json({ message: "Please complete every required field." });
    }

    if (!validEmail(email)) {
      return response.status(400).json({ message: "Please enter a valid email address." });
    }

    const reference = createReference("BC-S");

    await sendEmail({
      from: senderAddress(),
      to: [recruitmentAddress()],
      replyTo: email,
      subject: `Support request: ${subject} — ${name}`,
      html: emailLayout("New Support Request", `
        <p><strong>Support reference:</strong> ${reference}</p>
        <p><strong>Name:</strong> ${escapeHtml(name)}</p>
        <p><strong>Email:</strong> ${escapeHtml(email)}</p>
        <p><strong>Subject:</strong> ${escapeHtml(subject)}</p>
        <h2 style="font-size:17px;margin:26px 0 8px;color:#071a3b">Message</h2>
        <p style="white-space:pre-line;line-height:1.7">${escapeHtml(message)}</p>
      `)
    });

    try {
      await sendEmail({
        from: senderAddress(),
        to: [email],
        replyTo: recruitmentAddress(),
        subject: `Support request received — ${reference}`,
        html: emailLayout("Support Request Received", `
          <p style="font-size:16px;line-height:1.7">Dear ${escapeHtml(name)},</p>
          <p style="font-size:16px;line-height:1.7">Your support request has been received by Brownstone Careers.</p>
          <p style="font-size:16px;line-height:1.7"><strong>Reference:</strong> ${reference}</p>
          <p style="font-size:16px;line-height:1.7">A member of the recruitment support team will respond through an official email channel.</p>
          <p style="font-size:16px;line-height:1.7">Regards,<br><strong>Brownstone Careers Recruitment Team</strong></p>
        `)
      });
    } catch (confirmationError) {
      console.error("Support confirmation failed:", confirmationError.message);
    }

    return response.status(201).json({ success: true, reference });
  } catch (error) {
    console.error("Support submission error:", error);
    return response.status(502).json({
      message: "We could not deliver your message. Please try again or email support@brownstonecareers.agency."
    });
  }
});

app.use((error, _request, response, _next) => {
  console.error("Request error:", error);

  if (error instanceof multer.MulterError && error.code === "LIMIT_FILE_SIZE") {
    return response.status(400).json({ message: "The resume must be no larger than 5 MB." });
  }

  return response.status(400).json({
    message: error.message || "The request could not be processed."
  });
});

app.listen(port, () => {
  console.log(`Brownstone Careers is running on http://localhost:${port}`);
});
