/**
 * Brownstone Careers reusable email templates.
 * All templates render through one email-safe design system for Resend.
 */

const EMAIL_BRAND = Object.freeze({
  name: "Brownstone Careers",
  legalName: "Brownstone Careers Recruitment Agency",
  website: "https://brownstonecareers.agency",
  logo: "https://brownstonecareers.agency/assets/logo.png",
  primary: "#0B3B91",
  action: "#0B5FFF",
  background: "#F2F5FA",
  text: "#17233B",
  muted: "#667085",
});

function escapeEmailHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function emailButton(label, url) {
  if (!label || !url) return "";
  return `<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:26px auto"><tr><td bgcolor="${EMAIL_BRAND.action}" style="border-radius:8px"><a href="${escapeEmailHtml(url)}" target="_blank" style="display:inline-block;padding:15px 28px;color:#ffffff;text-decoration:none;font-size:16px;font-weight:700;border-radius:8px">${escapeEmailHtml(label)}</a></td></tr></table>`;
}

function detailCard(label, value) {
  return `<div style="margin:24px 0;padding:18px;background:#EEF3FB;border-left:4px solid ${EMAIL_BRAND.primary};border-radius:8px"><div style="font-size:12px;color:#5B6880;text-transform:uppercase;letter-spacing:.12em">${escapeEmailHtml(label)}</div><div style="font-size:21px;font-weight:800;color:#071A3B;margin-top:5px;word-break:break-word">${escapeEmailHtml(value)}</div></div>`;
}

function contentSection(title, value) {
  return `<h2 style="font-size:17px;margin:26px 0 8px;color:#071A3B">${escapeEmailHtml(title)}</h2><p style="white-space:pre-line;line-height:1.7;margin:0">${escapeEmailHtml(value)}</p>`;
}

function brandedEmailLayout({ title, preheader = "", content, footerNote = "" }) {
  const safeTitle = escapeEmailHtml(title);
  const safePreheader = escapeEmailHtml(preheader);
  return `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeTitle}</title></head>
<body style="margin:0;padding:0;background:${EMAIL_BRAND.background};font-family:Arial,Helvetica,sans-serif;color:${EMAIL_BRAND.text}">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">${safePreheader}</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:${EMAIL_BRAND.background}"><tr><td align="center" style="padding:30px 12px">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:680px;background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #DFE6F0">
<tr><td align="center" style="padding:28px 28px 24px;background:#ffffff;border-bottom:1px solid #E8EDF5"><a href="${EMAIL_BRAND.website}" target="_blank" style="text-decoration:none"><img src="${EMAIL_BRAND.logo}" width="260" alt="Brownstone Careers Recruitment Agency" style="display:block;width:260px;max-width:100%;height:auto;border:0;outline:none;text-decoration:none"></a></td></tr>
<tr><td style="padding:34px 32px"><h1 style="font-size:27px;line-height:1.25;margin:0 0 22px;color:#071A3B">${safeTitle}</h1>${content}</td></tr>
<tr><td align="center" style="padding:26px 32px;background:${EMAIL_BRAND.primary};color:#ffffff"><p style="margin:0 0 8px;font-size:17px;font-weight:700">${EMAIL_BRAND.name}</p><p style="margin:0 0 12px;color:#DBEAFE;font-size:13px">Real Talent. Real Careers. Real Impact.</p><a href="${EMAIL_BRAND.website}" target="_blank" style="color:#ffffff;text-decoration:none;font-size:13px">brownstonecareers.agency</a></td></tr>
<tr><td style="padding:16px 32px;background:#F7F9FC;color:${EMAIL_BRAND.muted};font-size:12px;line-height:1.6;text-align:center">${footerNote || "This email was generated by the official Brownstone Careers website. Never share passwords, PINs, or banking credentials."}</td></tr>
</table></td></tr></table></body></html>`;
}

function applicationReceivedEmail({ firstName, role, reference }) {
  const name = escapeEmailHtml(firstName || "Applicant");
  const safeRole = escapeEmailHtml(role || "selected");
  return brandedEmailLayout({
    title: "Application Received",
    preheader: `We received your application for ${role || "a Brownstone Careers opportunity"}.`,
    content: `<p style="font-size:16px;line-height:1.7;margin:0 0 18px">Dear ${name},</p><p style="font-size:16px;line-height:1.7;margin:0 0 18px">Thank you for applying for the <strong>${safeRole}</strong> opportunity with Brownstone Careers.</p>${detailCard("Application reference", reference)}<p style="font-size:16px;line-height:1.7;margin:0 0 18px">Our recruitment team will review your submission. Please keep this reference number for future correspondence.</p><p style="font-size:16px;line-height:1.7;margin:0">Regards,<br><strong>Brownstone Careers Recruitment Team</strong></p>`,
  });
}

function contactReceivedEmail({ name, reference }) {
  return brandedEmailLayout({
    title: "Your Message Was Received",
    preheader: "Your message has been delivered to the Brownstone Careers support team.",
    content: `<p style="font-size:16px;line-height:1.7;margin:0 0 18px">Dear ${escapeEmailHtml(name || "there")},</p><p style="font-size:16px;line-height:1.7;margin:0 0 18px">Thank you for contacting Brownstone Careers. Your message has been delivered to our support team.</p>${detailCard("Support reference", reference)}<p style="font-size:16px;line-height:1.7;margin:0">Regards,<br><strong>Brownstone Careers Support</strong></p>`,
  });
}

function internalApplicationEmail(data) {
  const content = `<p><strong>Application reference:</strong> ${escapeEmailHtml(data.reference)}</p><p><strong>Candidate:</strong> ${escapeEmailHtml(data.fullName)}</p><p><strong>Email:</strong> ${escapeEmailHtml(data.email)}</p><p><strong>Phone:</strong> ${escapeEmailHtml(data.phone)}</p><p><strong>Role:</strong> ${escapeEmailHtml(data.role)}</p><p><strong>Time zone:</strong> ${escapeEmailHtml(data.timezone)}</p><p><strong>Available start:</strong> ${escapeEmailHtml(data.startDate)}</p>${contentSection("Relevant experience", data.experience)}${contentSection("Interest in the role", data.interest)}${contentSection("Software and technical skills", data.skills)}${contentSection("Remote-work readiness", data.readiness)}`;
  return brandedEmailLayout({ title: "New Candidate Application", preheader: `${data.fullName} applied for ${data.role}.`, content });
}

function internalContactEmail({ reference, name, email, subject, message }) {
  return brandedEmailLayout({
    title: "New Website Support Request",
    preheader: `${name} submitted a new website message.`,
    content: `<p><strong>Support reference:</strong> ${escapeEmailHtml(reference)}</p><p><strong>Name:</strong> ${escapeEmailHtml(name)}</p><p><strong>Email:</strong> ${escapeEmailHtml(email)}</p><p><strong>Subject:</strong> ${escapeEmailHtml(subject)}</p>${contentSection("Message", message)}`,
  });
}

function preScreeningEmail({ firstName, role, actionUrl, deadline = "30 minutes" }) {
  return brandedEmailLayout({
    title: "Pre-Screening Invitation",
    preheader: `Complete your pre-screening for the ${role} position.`,
    content: `<p style="font-size:16px;line-height:1.7">Dear ${escapeEmailHtml(firstName)},</p><p style="font-size:16px;line-height:1.7">We are pleased to invite you to the pre-screening stage for the <strong>${escapeEmailHtml(role)}</strong> position.</p>${detailCard("Completion window", deadline)}<p style="font-size:16px;line-height:1.7">Please answer every question accurately and submit your responses within the stated window.</p>${emailButton("Begin Pre-Screening", actionUrl)}<p style="font-size:16px;line-height:1.7">Kind regards,<br><strong>Brownstone Careers Recruitment Team</strong></p>`,
  });
}

function interviewInviteEmail({ firstName, role, dateTime, location = "Microsoft Teams", actionUrl }) {
  return brandedEmailLayout({
    title: "Interview Invitation",
    preheader: `You have been invited to interview for the ${role} position.`,
    content: `<p style="font-size:16px;line-height:1.7">Dear ${escapeEmailHtml(firstName)},</p><p style="font-size:16px;line-height:1.7">We are pleased to invite you to an interview for the <strong>${escapeEmailHtml(role)}</strong> position.</p>${detailCard("Interview date and time", dateTime)}<p style="font-size:16px;line-height:1.7"><strong>Location:</strong> ${escapeEmailHtml(location)}</p>${emailButton("Confirm or Join Interview", actionUrl)}<p style="font-size:16px;line-height:1.7">Kind regards,<br><strong>Brownstone Careers Recruitment Team</strong></p>`,
  });
}

function offerLetterEmail({ firstName, role, startDate, actionUrl }) {
  return brandedEmailLayout({
    title: "Offer of Engagement",
    preheader: `Brownstone Careers has issued an offer for the ${role} position.`,
    content: `<p style="font-size:16px;line-height:1.7">Dear ${escapeEmailHtml(firstName)},</p><p style="font-size:16px;line-height:1.7">Congratulations. We are pleased to extend an offer for the <strong>${escapeEmailHtml(role)}</strong> position, subject to the terms, verification requirements, and agreement provided with your offer documentation.</p>${detailCard("Proposed start date", startDate)}${emailButton("Review Offer", actionUrl)}<p style="font-size:16px;line-height:1.7">Kind regards,<br><strong>Brownstone Careers Recruitment Team</strong></p>`,
  });
}

function recruitmentUpdateEmail({ firstName, title, message, actionLabel, actionUrl }) {
  return brandedEmailLayout({
    title,
    preheader: message,
    content: `<p style="font-size:16px;line-height:1.7">Dear ${escapeEmailHtml(firstName)},</p><p style="font-size:16px;line-height:1.7;white-space:pre-line">${escapeEmailHtml(message)}</p>${emailButton(actionLabel, actionUrl)}<p style="font-size:16px;line-height:1.7">Kind regards,<br><strong>Brownstone Careers Recruitment Team</strong></p>`,
  });
}

module.exports = { EMAIL_BRAND, escapeEmailHtml, emailButton, detailCard, contentSection, brandedEmailLayout, applicationReceivedEmail, contactReceivedEmail, internalApplicationEmail, internalContactEmail, preScreeningEmail, interviewInviteEmail, offerLetterEmail, recruitmentUpdateEmail };
